POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
  "username": "student2",
  "password": "admin@123"
}

###
POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "student2",
    "email": "stu@gmail.com",
    "password": "admin@123",
    "password2": "admin@123",
    "user_type": "student"
}

###
GET http://127.0.0.1:8000/auth/profile/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTg2MTk2LCJpYXQiOjE3NDY2NDA1OTYsImp0aSI6IjI3ZWE5NWE2ZGEwODQ0N2Y4MWNjNTA2ZGYzYzUyMzAwIiwidXNlcl9pZCI6OX0.sRc2NIV0N3T2s0BcpUdrYXMsY-I2iXvQCC_5H6kM6Zg

