POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
  "username": "student2",
  "password": "admin@123"
}

###
POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "student2",
    "email": "stu@gmail.com",
    "password": "admin@123",
    "password2": "admin@123",
    "user_type": "student"
}

###
GET http://127.0.0.1:8000/auth/profile/update/
Content-Type: application/json
Authorization: Bearer 